--- 
abstract: parameterized roles
author: 
  - Shawn M Moore <sartak@bestpractical.com>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.004
license: perl
name: MooseX-Role-Parameterized
requires: 
  Moose: 0.78
  Test::Exception: 0.27
version: 0.06
