---
abstract: 'roles with composition parameters'
author:
  - 'Shawn M Moore, C<sartak@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Fatal: 0
  Test::Moose: 0
  Test::More: '0.96'
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.10'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Role-Parameterized
no_index:
  directory:
    - inc
    - t
requires:
  Module::Runtime: 0
  Moose: '2.0300'
  perl: 5.8.1
resources:
  homepage: https://github.com/moose/MooseX-Role-Parameterized/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/moose/MooseX-Role-Parameterized.git
version: '1.03'
